/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    'documentation1':[

        {
            type:'category',
            label: 'Getting Started',
            link: {
                type: 'doc',
                id: 'getting-started/getting-started',  // Link to the overview page
              },
            items:[
              'getting-started/Setup',
                'getting-started/Starting Study Compass',
                'getting-started/Links',
            ]
        },

        {
            type:'category',
            label: "Development Guidelines",
            // link:{
            //     type:'doc',
            //     id:'Development Guidelines/General Contribution Guidelines'
            // },
            items:[
            'Development Guidelines/General Contribution Guidelines',
              'Development Guidelines/Naming Conventions',
              'Development Guidelines/Styling Conventions',
              'Development Guidelines/Bug Fixing Guidelines',
                'Development Guidelines/Mobile Development'
            ]
        },
        {
            type:'category',
            label: "Frontend",
            link:{
                type:'doc',
                id:'Frontend/Frontend'
            },
            items:[
                'Frontend/Room Page',
                'Frontend/Register Pages',
                'Frontend/SearchBar Component',
                'Frontend/Calendar & DayColumn Components',
                'Frontend/MobileCalendar Component',
                'Frontend/AuthProvider Component & AuthContext',
                'Frontend/CacheProvider Component & CacheContext',
                'Frontend/ErrorProvider Component & ErrorContext'

            ]
        },
        {
            type:'category',
            label: "Backend",
            link:{
                type:'doc',
                id:'Backend/Backend'
            },
            items:[
                'Backend/Backend Authentication Routes',
                'Backend/Backend Data Fetching Routes'
            ]
        },
        {
            type:'category',
            label: "Database",
            link:{
                type:'doc',
                id:'Database/Database'
            },
            items:[
                'Database/Setup and Running Migration Scripts',
                'Database/Database Versioning',
            ]
        }

    ],

  // But you can create a sidebar manually

  



};

export default sidebars;
