/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    'documentation1':[

        {
            type:'category',
            label: 'Getting Started',
            link: {
                type: 'doc',
                id: 'getting-started/getting-started',  // Link to the overview page
              },
            items:[
              'getting-started/Setup',
                'getting-started/Installation',
                'getting-started/Links',
            ]
        },

        {
            type:'category',
            label: "Development Guidelines",
            items:[
              'Development Guidelines/Naming Conventions',
              'Development Guidelines/Styling Conventions',
              'Development Guidelines/Bug Fixing Guidelines'
            ]
        }
    ],

  // But you can create a sidebar manually

  



};

export default sidebars;
